// HL7v2KitCodegen — emits Swift TypedSegment structs from schema JSON.
//
// Usage:
//   swift run HL7v2KitCodegen [<schemasRoot>] [<outputRoot>]
//
// Defaults:
//   schemasRoot: ./Resources/schemas
//   outputRoot:  ./Sources/HL7v2Kit/Segment/Generated
//
// The schemas root contains version directories (e.g. v2.5.1/) each with one
// JSON file per segment (e.g. PID.json). Each file is rendered to
//   <outputRoot>/<VersionDir>/<SegmentID>.swift
// Existing files are overwritten — the generated tree is intended to be
// owned by this tool, not edited by hand.

import Foundation

struct FieldSchema: Decodable {
    let index: Int
    let swiftName: String
    let name: String
    let dataType: String
    let optionality: String
    let repeatability: String
    /// Optional predicate string controlling when a `.conditional` field
    /// becomes required. See `FieldGrammar.condition` for the grammar.
    /// v0.2-V1.
    let condition: String?
}

struct SegmentSchema: Decodable {
    let segmentID: String
    let version: String
    let description: String
    let fields: [FieldSchema]
}

/// HL7 data type codes whose values are scalar enough that the typed
/// accessor returns `String?` (the flattened first-subcomponent value).
/// Everything else returns `Field?` and the caller reaches into components.
let scalarDataTypes: Set<String> = [
    "SI", "ID", "IS", "ST", "NM", "DT", "TM", "TS", "FT", "GTS", "TX", "DTM",
]

func swiftAccessor(for field: FieldSchema, segmentID: String) -> String {
    let returnsString = scalarDataTypes.contains(field.dataType)
    let returnType = returnsString ? "String?" : "Field?"
    let body = returnsString
        ? "field(\(field.index))?.stringValue"
        : "field(\(field.index))"
    return """
        /// \(segmentID)-\(field.index): \(field.name). HL7 data type `\(field.dataType)`.
        public var \(field.swiftName): \(returnType) {
            \(body)
        }
    """
}

func render(_ schema: SegmentSchema) -> String {
    let accessors = schema.fields
        .map { swiftAccessor(for: $0, segmentID: schema.segmentID) }
        .joined(separator: "\n\n")

    return """
    // Auto-generated by HL7v2KitCodegen. Do not edit by hand.
    // Source schema: Resources/schemas/v\(schema.version)/\(schema.segmentID).json
    // Regenerate via scripts/regenerate-typed-segments.sh

    import Foundation

    /// \(schema.description) segment (HL7 v\(schema.version)).
    public struct \(schema.segmentID): TypedSegment, Sendable, Equatable, Hashable {
        public static let segmentID = "\(schema.segmentID)"
        public let fields: [Field]

        public init(fields: [Field]) {
            self.fields = fields
        }

    \(accessors)
    }

    """
}

func versionDirName(_ version: String) -> String {
    // v2.5.1 → v2_5_1 (legal Swift identifier piece)
    "v" + version.replacingOccurrences(of: ".", with: "_")
}

/// Emit the codegen-side `SegmentRegistry` extension. Cases are sorted
/// alphabetically by segment ID so the output is deterministic.
func renderRegistry(segmentIDs: [String]) -> String {
    let cases = segmentIDs.sorted().map { id in
        "        case \(id).segmentID: return .typed(AnyTypedSegment(\(id)(fields: unknown.fields)))"
    }.joined(separator: "\n")

    return """
    // Auto-generated by HL7v2KitCodegen. Do not edit by hand.
    // This extension is the source of truth for typed-segment hydration.
    // To register a new segment, add its JSON schema under Resources/schemas/
    // and run scripts/regenerate-typed-segments.sh.

    import Foundation

    extension SegmentRegistry {
        /// Hydrate `unknown` into a `.typed` segment if its ID matches a
        /// schema-emitted typed struct. Returns nil for unrecognised IDs so
        /// the caller can fall back to `.unknown` (Z-segment tolerance).
        static func hydrateGenerated(_ unknown: UnknownSegment) -> Segment? {
            switch unknown.segmentID {
    \(cases)
            default:
                return nil
            }
        }
    }

    """
}

/// Emit the validator's per-version `SegmentGrammar` table. The validator
/// reads from this table at runtime — no JSON parsing, no extra bundle.
/// Schemas are sorted by segment ID and fields by ascending `index` so the
/// output is deterministic.
func renderGrammarTable(version: String, schemas: [SegmentSchema]) -> String {
    let versionSwiftName = "v" + version.replacingOccurrences(of: ".", with: "_")
    let entries = schemas.sorted(by: { $0.segmentID < $1.segmentID }).map { schema in
        let fields = schema.fields.sorted(by: { $0.index < $1.index }).map { field in
            let repeatability = field.repeatability == "*" ? ".multiple" : ".single"
            let condition = field.condition.map { escapeStringLiteral($0) } ?? "nil"
            return "            FieldGrammar(index: \(field.index), name: \(escapeStringLiteral(field.name)), dataType: \(escapeStringLiteral(field.dataType)), optionality: .\(optionalityCase(field.optionality)), repeatability: \(repeatability), condition: \(condition)),"
        }.joined(separator: "\n")
        return """
                "\(schema.segmentID)": SegmentGrammar(
                    segmentID: "\(schema.segmentID)",
                    version: "\(schema.version)",
                    fields: [
        \(fields)
                    ]
                ),
        """
    }.joined(separator: "\n")

    return """
    // Auto-generated by HL7v2KitCodegen. Do not edit by hand.
    // Validator looks segments up here at runtime — no JSON parsing needed.
    // To extend a segment's grammar, edit its JSON schema under
    // Resources/schemas/ and run scripts/regenerate-typed-segments.sh.

    import Foundation

    extension SegmentGrammarTable {
        public static let \(versionSwiftName): [String: SegmentGrammar] = [
    \(entries)
        ]
    }

    """
}

/// Map a single-letter HL7 optionality code to a Swift enum case name.
func optionalityCase(_ code: String) -> String {
    switch code {
    case "R": return "required"
    case "O": return "optional"
    case "C": return "conditional"
    case "X": return "notSupported"
    case "B": return "backwardCompat"
    default:  return "optional"   // Default to permissive on unknown codes.
    }
}

/// Render a Swift string literal that round-trips the input value safely
/// (handles backslash and quote characters).
func escapeStringLiteral(_ s: String) -> String {
    let escaped = s
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"")
    return "\"\(escaped)\""
}

@main
struct Codegen {
    static func main() throws {
        let args = CommandLine.arguments
        let cwd = FileManager.default.currentDirectoryPath
        let schemasRoot = URL(fileURLWithPath: args.count > 1 ? args[1] : "\(cwd)/Resources/schemas")
        let outputRoot = URL(fileURLWithPath: args.count > 2 ? args[2] : "\(cwd)/Sources/HL7v2Kit/Segment/Generated")

        let fm = FileManager.default

        let versionDirs = try fm.contentsOfDirectory(at: schemasRoot, includingPropertiesForKeys: nil)
            .filter { (try? $0.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) ?? false }

        guard !versionDirs.isEmpty else {
            FileHandle.standardError.write(Data("HL7v2KitCodegen: no version directories under \(schemasRoot.path)\n".utf8))
            throw ExitCode.failure
        }

        var emitted = 0
        var emittedSegmentIDs: Set<String> = []
        var schemasByVersion: [String: [SegmentSchema]] = [:]
        for versionURL in versionDirs.sorted(by: { $0.lastPathComponent < $1.lastPathComponent }) {
            let version = versionURL.lastPathComponent.replacingOccurrences(of: "v", with: "", options: [.anchored])
            let segmentFiles = try fm.contentsOfDirectory(at: versionURL, includingPropertiesForKeys: nil)
                .filter { $0.pathExtension == "json" }
                .sorted(by: { $0.lastPathComponent < $1.lastPathComponent })

            let outVersionDir = outputRoot.appendingPathComponent(versionDirName(version))
            try fm.createDirectory(at: outVersionDir, withIntermediateDirectories: true)

            for schemaURL in segmentFiles {
                let data = try Data(contentsOf: schemaURL)
                let schema = try JSONDecoder().decode(SegmentSchema.self, from: data)
                let source = render(schema)
                let outFile = outVersionDir.appendingPathComponent("\(schema.segmentID).swift")
                try Data(source.utf8).write(to: outFile)
                print("emitted \(outFile.path)")
                emitted += 1
                emittedSegmentIDs.insert(schema.segmentID)
                schemasByVersion[version, default: []].append(schema)
            }
        }

        // Emit the cross-version SegmentRegistry extension.
        try fm.createDirectory(at: outputRoot, withIntermediateDirectories: true)
        let registrySource = renderRegistry(segmentIDs: Array(emittedSegmentIDs))
        let registryFile = outputRoot.appendingPathComponent("SegmentRegistry+Generated.swift")
        try Data(registrySource.utf8).write(to: registryFile)
        print("emitted \(registryFile.path)")

        // Emit the per-version SegmentGrammar table consumed by Validator.
        for (version, schemas) in schemasByVersion.sorted(by: { $0.key < $1.key }) {
            let grammarSource = renderGrammarTable(version: version, schemas: schemas)
            let grammarFile = outputRoot.appendingPathComponent("SegmentGrammar+\(versionDirName(version)).swift")
            try Data(grammarSource.utf8).write(to: grammarFile)
            print("emitted \(grammarFile.path)")
        }

        print("HL7v2KitCodegen: \(emitted) segment(s) emitted under \(outputRoot.path)")
    }
}

enum ExitCode: Error { case failure }
