// GeneratedOutput.swift
// Writes one generated output directory all-or-nothing: every file is rendered
// before this is called, and every check runs before anything is written, so a
// failure leaves the directory untouched. A file there that the run did not
// produce is stale (a segment or composite whose schema was removed or renamed)
// and is deleted, so the directory equals the run's output and the codegen-drift
// check sees a stale committed file as a deletion.
//
// Deletion is guarded twice. The directory's last path component must be
// `Generated` (a wrong output argument such as `Sources/HL7v2Kit/Segment` is
// refused), and only a regular `.swift` file that starts with
// `generatedHeader` is removed. Any other entry the run did not produce (a
// non-Swift file, a subdirectory, a Swift file without the header) fails the
// run, naming it: it is neither silently kept nor silently removed.

import Foundation

/// The first line of every file the generator writes.
let generatedHeader = "// Auto-generated by HL7v2KitCodegen. Do not edit by hand."

/// Writes `rendered` into `directory`, then deletes every generated file there that the run did not produce.
func writeGeneratedDirectory(_ rendered: [(file: URL, source: String)], into directory: URL) throws {
    let fm = FileManager.default
    guard directory.standardizedFileURL.lastPathComponent == "Generated" else {
        throw outputFailure("refusing to manage \(directory.path): an output directory must be named Generated")
    }
    let unheadered = rendered.filter { !$0.source.hasPrefix(generatedHeader) }.map { $0.file.lastPathComponent }
    guard unheadered.isEmpty else {
        throw outputFailure("rendered \(unheadered) without the generator header")
    }
    let produced = Set(rendered.map { $0.file.lastPathComponent })
    let existing = fm.fileExists(atPath: directory.path)
        ? try fm.contentsOfDirectory(atPath: directory.path).sorted() : []
    var stale: [URL] = []
    var foreign: [String] = []
    // Hidden entries (a Finder `.DS_Store`) are neither generated nor source: left alone.
    for entry in existing where !produced.contains(entry) && !entry.hasPrefix(".") {
        let url = directory.appendingPathComponent(entry)
        if isGeneratedFile(url) { stale.append(url) } else { foreign.append(url.path) }
    }
    guard foreign.isEmpty else {
        throw outputFailure("\(directory.path) holds entries the generator did not write: "
            + foreign.joined(separator: ", ") + ". Move or delete them by hand.")
    }
    try fm.createDirectory(at: directory, withIntermediateDirectories: true)
    for (outFile, source) in rendered {
        try Data(source.utf8).write(to: outFile)
        print("emitted \(outFile.path)")
    }
    for url in stale {
        try fm.removeItem(at: url)
        print("removed stale \(url.path)")
    }
}

/// A regular `.swift` file whose first line is `generatedHeader`.
private func isGeneratedFile(_ url: URL) -> Bool {
    guard url.pathExtension == "swift",
          (try? url.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true,
          let handle = try? FileHandle(forReadingFrom: url) else { return false }
    defer { try? handle.close() }
    let head = (try? handle.read(upToCount: generatedHeader.utf8.count)) ?? Data()
    return String(decoding: head, as: UTF8.self) == generatedHeader
}

private func outputFailure(_ message: String) -> ExitCode {
    FileHandle.standardError.write(Data("HL7v2KitCodegen: \(message)\n".utf8))
    return ExitCode.failure
}
